### ISSUE TITLE
remove versions from packagist

### ISSUE THREAD

**Issue by svycka** [Laminas-Commons/LmcRbac#13]
```
# composer require laminas-commons/lmc-rbac
Using version ^2.6 for laminas-commons/lmc-rbac
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing zfr/rbac (1.2.0): Downloading (100%)         
  - Installing laminas-commons/lmc-rbac (v2.6.3): Downloading (100%)      
```
I had to install with version to get the correct version `composer require laminas-commons/lmc-rbac:^1.0`
this can lead to big problems

**Comment by basz** [comment]
Can we trigger a update on packagist manually? Linkage seem broken...

**Comment by basz** [comment]
I wonder from where these packages are downloaded from as the releases have been removed from github...

**Comment by svycka** [comment]
auto-update only removes branches but not tags. Tags have to be removed by hand in https://packagist.org/packages/laminas-commons/lmc-rbac

**Comment by svycka** [comment]
@visto9259 I guess only you can remove them

**Comment by visto9259** [comment]
Done.
Who wants to be added as a maintainer on packagist for the repo?

**Comment by basz** [comment]
i do
